[versions]
vKotlin = "2.0.20"
vCoroutines = "1.9.0"
vSerialization = "1.7.3"
vDateTime = "0.6.1"
vSlf4j = "2.1.0-alpha1"
vMockito = "5.4.0"

[libraries]
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "vKotlin" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "vCoroutines" }
json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "vSerialization" }
datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "vDateTime" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "vKotlin" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "vSlf4j" }
mockito = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "vMockito" }

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "vKotlin"}
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "vKotlin" }
